server {
    listen 80;

    client_max_body_size 100M;
    
    # Directorio donde Nginx sirve los archivos estáticos
    root /usr/share/nginx/html;
    index index.html;

        # NUEVO: Regla de Proxy para MinIO
    location /minio-api/ {
        # Como Nginx está dentro de Docker, sí conoce la palabra 'minio'
        proxy_pass http://minio:9000/;
        proxy_set_header Host minio:9000; # Mantiene la firma válida
    }

    # NUEVO: Regla de Proxy para el Gateway (Backend)
    location /api/ {
        # Nginx reenviará esto al servicio "gateway" definido en el docker-compose
        proxy_pass http://gateway:8001/api/;
        
        # Mantiene las cabeceras originales
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }


    location / {
        # La magia de React Router ocurre aquí:
        # Intenta cargar el archivo ($uri), luego el directorio ($uri/)
        # y si no encuentra ninguno, redirige a /index.html
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Configuración para manejar errores 500
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}


