server {
    listen 80;
    
    # Directorio donde Nginx sirve los archivos estáticos
    root /usr/share/nginx/html;
    index index.html;

        # NUEVO: Regla de Proxy para MinIO
    location /minio-api/ {
        # Como Nginx está dentro de Docker, sí conoce la palabra 'minio'
        proxy_pass http://minio:9000/;
        proxy_set_header Host minio:9000; # Mantiene la firma válida
    }

    location / {
        # La magia de React Router ocurre aquí:
        # Intenta cargar el archivo ($uri), luego el directorio ($uri/)
        # y si no encuentra ninguno, redirige a /index.html
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Configuración para manejar errores 500
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}


